name: tron_codec
version: 0.1.3

dependencies:
  bs58: ^1.0.1
  convert: ^2.1.1
  protobuf: ^1.1.4
  typed_data: ^1.2.0
  ethereum_util:
    git:
      url: https://github.com/ethereumdart/ethereum_util

dev_dependencies: 
  meta: 1.3.0
  test: 1.16.5

environment:
  sdk: ">=1.19.0 <3.0.0"
