name: tron_codec
version: 2.0.0

dependencies:
  bs58: ^1.0.2
  convert: ^3.0.0
  protobuf: ^2.0.0
  typed_data: ^1.3.0
  quiver: ^3.0.0
  pointycastle: ^3.6.0

dev_dependencies: 
  meta: any
  test: any

environment:
  sdk: ">=2.12.0 <3.0.0"
